services:
  back:
    image: back_image
    build:
      context: .
      dockerfile: ./backend/docker/django/Dockerfile
      cache_from:
        - back_image
    container_name: back-v1
#    command: sh ./docker/django/gunicorn.sh
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./backend/src:/code
      - ./backend/search_dir:/search_dir
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db-v1
    restart: always
    ports:
      - '5434:5432'
    env_file:
      - ./backend/.env

volumes:
  db_data:
