services:
  back:
    image: back_image
    build:
      context: .
      dockerfile: ./backend/docker/django/Dockerfile
      cache_from:
        - back_image
    container_name: back-v1
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./backend/src:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db

  scheduler:
    image: scheduler_image
    build:
      context: .
      dockerfile: ./backend/docker/django/Dockerfile
    container_name: scheduler-v1
    command: python manage.py run_huey
    volumes:
      - ./backend/src:/code
      - ./backend/search_dir:/search_dir
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db-v1
    restart: always
    ports:
      - '5434:5432'
    env_file:
      - ./backend/.env

  redis:
    image: redis:alpine
    container_name: redis-v1
    volumes:
      - ./storage/redis:/data

volumes:
  db_data:
