# Generated by Django 5.1.2 on 2024-10-24 17:22

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('text', models.TextField(blank=True, help_text='Текст, который должен содержаться в файле', verbose_name='Текст')),
                ('file_mask', models.CharField(blank=True, max_length=255, verbose_name='Маска имени файла')),
                ('size', models.PositiveIntegerField(null=True, verbose_name='Размер файла')),
                ('size_option', models.CharField(blank=True, choices=[('EQ', 'Равно'), ('GT', 'Больше'), ('LT', 'Меньше'), ('GE', 'Больше или равно'), ('LE', 'Меньше или равно')], max_length=10, verbose_name='Оператор сравнения размера')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='Дата создания')),
                ('creation_date_option', models.CharField(blank=True, choices=[('EQ', 'Равно'), ('GT', 'Больше'), ('LT', 'Меньше'), ('GE', 'Больше или равно'), ('LE', 'Меньше или равно')], max_length=10, verbose_name='Оператор сравнения размера')),
            ],
            options={
                'verbose_name': 'Параметры фильтрации',
                'verbose_name_plural': 'Параметры фильтрации',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('size__isnull', True), ('size_option__exact', '')), models.Q(('size__isnull', False), ('size_option__isnull', False)), _connector='OR'), name='size_and_option_both_null_or_both_filled'), models.CheckConstraint(condition=models.Q(models.Q(('creation_date__isnull', True), ('creation_date_option__exact', '')), models.Q(('creation_date__isnull', False), ('creation_date_option__isnull', False)), _connector='OR'), name='creation_date_and_option_both_null_or_both_filled')],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Поле будет изменено при обновлении любого из полей модели.', null=True, verbose_name='Дата последнего обновления')),
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор запроса')),
                ('finished', models.BooleanField(default=False, verbose_name='Поиск завершен')),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('search_filter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to='searches.searchfilter')),
            ],
            options={
                'verbose_name': 'Поисковой запрос',
                'verbose_name_plural': 'Поисковые запросы',
            },
        ),
    ]
