# Generated by Django 5.1.2 on 2024-10-24 18:44

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchfilter',
            name='size_and_option_both_null_or_both_filled',
        ),
        migrations.RemoveConstraint(
            model_name='searchfilter',
            name='creation_date_and_option_both_null_or_both_filled',
        ),
        migrations.RenameField(
            model_name='searchfilter',
            old_name='creation_date_option',
            new_name='creation_date_operator',
        ),
        migrations.RenameField(
            model_name='searchfilter',
            old_name='size_option',
            new_name='size_operator',
        ),
        migrations.AddConstraint(
            model_name='searchfilter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('size__isnull', True), ('size_operator__exact', '')), models.Q(('size__isnull', False), ('size_operator__isnull', False)), _connector='OR'), name='size_and_operator_both_null_or_both_filled'),
        ),
        migrations.AddConstraint(
            model_name='searchfilter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('creation_date__isnull', True), ('creation_date_operator__exact', '')), models.Q(('creation_date__isnull', False), ('creation_date_operator__isnull', False)), _connector='OR'), name='creation_date_and_operator_both_null_or_both_filled'),
        ),
    ]
