# Generated by Django 5.1.2 on 2024-10-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_remove_searchfilter_size_and_option_both_null_or_both_filled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfilter',
            name='creation_date_operator',
            field=models.CharField(blank=True, choices=[('EQ', '=='), ('GT', '>'), ('LT', '<'), ('GE', '>='), ('LE', '<=')], max_length=10, verbose_name='Оператор сравнения размера'),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='size_operator',
            field=models.CharField(blank=True, choices=[('EQ', '=='), ('GT', '>'), ('LT', '<'), ('GE', '>='), ('LE', '<=')], max_length=10, verbose_name='Оператор сравнения размера'),
        ),
    ]
